PREFIX daq:		<http://purl.org/eis/vocab/daq#>
PREFIX prov:		<http://www.w3.org/ns/prov#>
PREFIX rdf:		<http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs:		<http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd:		<http://www.w3.org/2001/XMLSchema#>

ASK {
	 %metric-observation% a daq:Observation ;
	 	prov:generated ?profile .
} 
		