/* CVS $Id: $ */
package io.github.luzzu.semantics.vocabularies; 
import org.apache.jena.rdf.model.*;
 
/**
 * Vocabulary definitions from lqm.ttl 
 * @author Auto-generated by schemagen on 14 Aug 2018 16:00 
 */
public class LQM {
    /** <p>The RDF model that holds the vocabulary terms</p> */
    private static final Model M_MODEL = ModelFactory.createDefaultModel();
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://theme-e.adaptcentre.ie/lqm#";
    
    /** <p>The namespace of the vocabulary as a string</p>
     * @return namespace as String
     * @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = M_MODEL.createResource( NS );
    
    public static final Property hasCountMetric = M_MODEL.createProperty( "http://theme-e.adaptcentre.ie/lqm#hasCountMetric" );
    
    public static final Property hasSyntaxErrors = M_MODEL.createProperty( "http://theme-e.adaptcentre.ie/lqm#hasSyntaxErrors" );
    
    public static final Property hasVolumeDimension = M_MODEL.createProperty( "http://theme-e.adaptcentre.ie/lqm#hasVolumeDimension" );
    
    /** <p>Determines the total number of data lines (or triples in Linked Data) assessed.</p> */
    public static final Resource CountMetric = M_MODEL.createResource( "http://theme-e.adaptcentre.ie/lqm#CountMetric" );
    
    /** <p>The under-assessed dataset has syntactic error and cannot be fully parsed.</p> */
    public static final Resource SyntaxErrorProblem = M_MODEL.createResource( "http://theme-e.adaptcentre.ie/lqm#SyntaxErrorProblem" );
    
    /** <p>Determines whether the assessed dataset has syntax errors and thus the quality 
     *  assessment could not be done.</p>
     */
    public static final Resource SyntaxErrorsMetric = M_MODEL.createResource( "http://theme-e.adaptcentre.ie/lqm#SyntaxErrorsMetric" );
    
    /** <p>Groups metrics related to the volume/size of a data source.</p> */
    public static final Resource Volume = M_MODEL.createResource( "http://theme-e.adaptcentre.ie/lqm#Volume" );
    
}
